language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
before_script:
- bundle exec rails db:create --all
- bundle exec rails db:migrate
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: gmkZEmD7ZJG3f1OCTcbSUUkODEcxTTy/Uu4vH4iLYlGPG1KKuXLXMLHjiOllJuQOemI41HAoT6R3GaMpq77+W6HHYZihJo7VBgpDYuAT/FruaKlGbm/gBjsm7HxazM+rTgTz85oaS4UlLQsKf1WIoToN9XS5B1Rn8RaSjCDESHehTGAjY8fDWcYYc6/gqQgmXKIAmDurm3vjICQsgSWyTxLft+YV/0uLkmoHyaaTGU45/1cIXC3fgWPhEE0uYKVHajp9B9X8RshBYV6ECHlk4Hr2/295IMvR/ELd/0Bgw3HbDeqZg3+a87sK76k0WxMiubL0K+DEH7hLhD4zS34wjqAeRdIPUJs/gEb+Fahstsvdy8G1hpF2TOB3euQRye722KTBN94biX5Km07JTKMy2nfjmIZwDbuSjjsUKDqO9NHX4kfm/ZTS+tblcGAPOsogF8AdpCdzrbsBG7WLr8XvXiTebzlyNeJ0UZ+eJMxjiCabKI0iQvmB1BZDxzNLTltl6Hq7GwtX3U37zKFgWeHoZTe4TJFdJZxLN3Jfi6q+eq4glRRkzvS0Q8Fty8YS7zJZbfiZxdlIk1nR872+2G0B+wasZXG29VR4k8d9ddSfYQd8cmyHw1FUofdOWVqg76HlH54/6PoOm4yjJhC5sWG6S5FJz+5Oo1g0UIwJGJ9SEwY=
  app: limitless-harbor-80092
  on:
    repo: sgraton/AirPikachu
  run:
  - rails db:migrate
env:
  secure: YPhq6UkHLEaWpl117JwBnMKv4/QzVdlaUQffYt/KMLFWpshIYMs6lW4wGmYDVer+ZuTeA08gnZ9NUolwIDtr/AMUAVdvAe+tMlJ+e4JDyObJKrYe9bqeZot8R0CKFTVUd86W0ya9OAXTh2ltpBQFNxmsnmkMY9GaUK3Jef0ACWLpzg6VsISHMUyDAw9tSU8lSaxXca23UkqHFN7+djkxaAfNw11QbocQUsxwybHweTdXu84lZSZMQjGp/OSDJcwFRPVANZ8xVCPw/lom/fGZj73sSO6fkY4FaqLxwLDBfXfmzu5mrYIjRB8b1HfRAvYw/Z/5UpHVtF/3njmatpoDZEvWp5KE5Src1Oi56b818FfETzgnx/whnGh08U7P+AOGWNHBa1uphDRgo+4P+B5dFRxMMA9HIaqU1Sw5iU1LDclggXQjnSV7fLsCF5KjQecjNLjIRLbtWYjxpBNXZvYgA6+x23KpIpdh9MB49XYXJLP/+6Z2b42xb/jElo8kLXIaQxXKs3NnC6d6QJpglh2uDQhEnzMKH4ZEfEUKoMlq1JwnKRPLQZ8z39YEHxttTdVZAdr2mxlUMLhquU9tgTyxjzZSrlkoNNDqUdcDet6H6dS/zHcgS2uX4MJCUx68I90QmV9fXsPHVqaDQwoJlFQ6XgLXK1HaE3LCONPj4qGR8gQ=
