language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
before_script:
- bundle exec rails db:create --all
- bundle exec rails db:migrate
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: lpQdZr9XNzZXwsnLKjcxTWueBOr+UHgcfHvh9wrOU+L3cyteXOLX6GJ/3V6inCFQYMln41RV6Xq6mjZcEIftCykwuW0pVtDwGIeZ34kwV1ojk5f4B7VdnfB7mNvaqnhnDL/sOR2ylmoz6QDiT2wd4TEk7gRkf0yd+igs8QG8/SKjRM7xoCYXs6CQ16BnB2aZjJ+4FhDFPZP+59lNtZ7PhWZZIneKrwjJTrfUjEmmMnZ4truMo9umT+1+nDp4EfH0Nszivc/T1UrYuDqqA1sSxSW57tZZi/hhJT0BqwT0q1nKRawbHj2/SyzqaJrGk8q2xhNdvtcWa9TIlQNhuJtUZBC2RvG8qCuWw+bqmQ5mvt13wz8It2JzSQN/nVksixsFsg/9XxB8cux/2KYfR2RrET9MupQCur+lgBicA3e7dbKsRgU05efXzNxYyM54C1JQ43xbHm2DPOnWOkdT/cSleTt7KTJ6wMLsKtsg4srkxbwQSdJXapnF7goZRU+TrknCrpVucSJP9FSiE+7MmVxpRZVPnRcYKVAx8Do7xzZtDrKt3iUkiu3+BlzLfg11xntYK1QJrBRv789LdQPANeWUX3QRwEhkH4WZ0+2CXnDpImkR3fNch5c8objZtD908gxrCkzbL7d3ejRQckxYsJkaw28DAbJtDo/kKuUciZ9x1lk=
  app: limitless-harbor-80092
  on:
    repo: sgraton/AirPikachu
  run:
  - rails db:migrate
env:
  secure: YPhq6UkHLEaWpl117JwBnMKv4/QzVdlaUQffYt/KMLFWpshIYMs6lW4wGmYDVer+ZuTeA08gnZ9NUolwIDtr/AMUAVdvAe+tMlJ+e4JDyObJKrYe9bqeZot8R0CKFTVUd86W0ya9OAXTh2ltpBQFNxmsnmkMY9GaUK3Jef0ACWLpzg6VsISHMUyDAw9tSU8lSaxXca23UkqHFN7+djkxaAfNw11QbocQUsxwybHweTdXu84lZSZMQjGp/OSDJcwFRPVANZ8xVCPw/lom/fGZj73sSO6fkY4FaqLxwLDBfXfmzu5mrYIjRB8b1HfRAvYw/Z/5UpHVtF/3njmatpoDZEvWp5KE5Src1Oi56b818FfETzgnx/whnGh08U7P+AOGWNHBa1uphDRgo+4P+B5dFRxMMA9HIaqU1Sw5iU1LDclggXQjnSV7fLsCF5KjQecjNLjIRLbtWYjxpBNXZvYgA6+x23KpIpdh9MB49XYXJLP/+6Z2b42xb/jElo8kLXIaQxXKs3NnC6d6QJpglh2uDQhEnzMKH4ZEfEUKoMlq1JwnKRPLQZ8z39YEHxttTdVZAdr2mxlUMLhquU9tgTyxjzZSrlkoNNDqUdcDet6H6dS/zHcgS2uX4MJCUx68I90QmV9fXsPHVqaDQwoJlFQ6XgLXK1HaE3LCONPj4qGR8gQ=
  global:
    secure: joj/TV+UqOEa6qHqBaRJz5QSdz5ZE0NWKJmsmCN64VJoAHM3Qp6FqKNo7xFWKkWsaSeqB6JNTKGCTDGMaQVIlhsKEPcZ8x0OHfy1DJu7hbR2hOt77vitydpN0lTmzP3sLR72+3Rt7TJdVDTEe63btwQZkS3IjgpJZbKHOIOs554L4H+x64AT+zpWPJHziGdhS0lEEJlQs/xB2/Bwc6rFFzh4+a1yBA81kUds2o5iF37NXB2UfJ9D1BPfFtVFMmfZOt3qgsNOVlijE/GqdAoa8jYQo0dsQtx3EQCupS372chbIw3YEjxW/IpZaA3StepGhzdtK0ydgL0qJCE7LO7MRAWqykDV1tzvhjaWtJXqvttr443LX/ORm2xBnpYBI3vcoxT8mDPkcgqZqyZlxO2lDkRF15SL3lEdN6vwEwuV0kwcB9onTEtTPByNK2GITAK2g85KOvpPt1DsZvL0YHfYIgqtJcypltbKh4s5j3IFLI0CZFKMd3WdjXf49VYSERdWBiq0DkgrwcJuu+EHTS2ccUp0qK6xiIjS0I5ekgidED2KgJOotp1mlipOONmXHfctkSk2uIgTY5A9wsitlRXEZ/nurk8pnnoQs/PKSogiY76Zfjth2x3caLIzFiOW5e8T4fTaky60fP1ekagv1frfBS3sAOE3wPTGjKCMnCTE/vU=
