language: ruby
rvm:
- 2.6.2
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
before_script:
- bundle exec rails db:create --all
- bundle exec rails db:migrate
deploy:
  provider: heroku
  api_key:
    secure: lpQdZr9XNzZXwsnLKjcxTWueBOr+UHgcfHvh9wrOU+L3cyteXOLX6GJ/3V6inCFQYMln41RV6Xq6mjZcEIftCykwuW0pVtDwGIeZ34kwV1ojk5f4B7VdnfB7mNvaqnhnDL/sOR2ylmoz6QDiT2wd4TEk7gRkf0yd+igs8QG8/SKjRM7xoCYXs6CQ16BnB2aZjJ+4FhDFPZP+59lNtZ7PhWZZIneKrwjJTrfUjEmmMnZ4truMo9umT+1+nDp4EfH0Nszivc/T1UrYuDqqA1sSxSW57tZZi/hhJT0BqwT0q1nKRawbHj2/SyzqaJrGk8q2xhNdvtcWa9TIlQNhuJtUZBC2RvG8qCuWw+bqmQ5mvt13wz8It2JzSQN/nVksixsFsg/9XxB8cux/2KYfR2RrET9MupQCur+lgBicA3e7dbKsRgU05efXzNxYyM54C1JQ43xbHm2DPOnWOkdT/cSleTt7KTJ6wMLsKtsg4srkxbwQSdJXapnF7goZRU+TrknCrpVucSJP9FSiE+7MmVxpRZVPnRcYKVAx8Do7xzZtDrKt3iUkiu3+BlzLfg11xntYK1QJrBRv789LdQPANeWUX3QRwEhkH4WZ0+2CXnDpImkR3fNch5c8objZtD908gxrCkzbL7d3ejRQckxYsJkaw28DAbJtDo/kKuUciZ9x1lk=
  app: limitless-harbor-80092
  on:
    repo: sgraton/AirPikachu
  run:
  - rails db:migrate
env:
  secure: AlfHav+YuDsb0xAc5Fl4O7xBiBdkWPzPQ1/zF1dsL/zErUyozc6fMtoq+jFhKtos9pCYpme5oRoOiXN1duPKo+XYdJysIxVPMTfPKzTJNygwKDhmzrD+FY8T1kdxC5tTX2WER7a98zK3plsYs1afxgsEx35tyDHNWNDjORlLaIxyVF7AHuy/BfIaQJfjdIn+hpwNT22ksokwVr5Y7vOWQonGXFcRv9trZC3LnoD7AHr3M/4zj1lHMI2jQIUaRN1hAwikcOmMhWdSKRnuw2xF3fPNel2fRoKKuFxQ8qzovd05JfSZa8uGeh/OBaOW0CgHtKZJNcIT8eCecL5p7y5C0sTNMBtiqCP1MmEyVkNJQFycHWB2LTt3OYePPXQ31GPtMD4gvOnEzEPA7Ciu9V7n0lJqOdJhpfis75RRCjsvqhHL3yXfK0u279doFtG6G+AZdoLawSM1yoIlZW95tHe85RHVCmBaqcpXksVJD8xtk/20fnfvqDswGLcEue5HZZmmn6ly4wmoKRVF3MtuOTxwzDzcCbxeg6C1zN5/RLzYJ3DQKzbwY9kR0OlfmFq6tPli6DmLO2cIJOkZTWTB5qp7qeBxYqlDm/1NjhZ1Hi3+BIZOntsd/hdOATrxd+ZX4TrEHxmQ/uDHL5jybQrWNX2oVrnz2C4p0jAdcOlHLAKpMnk=
