default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: airpikachu_development

test:
  <<: *default
  database: airpikachu_test

production:
  database: airpikachu_production
  username: airpikachu
  password: <%= ENV['AIRPIKACHU_DATABASE_PASSWORD'] %>
